version: "1"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - db